format = "$git_branch$directory$git_status\n\n    $character"
add_newline = false

[directory]
style = "fg:#8F929B"
format = " [$path]($style)[$read_only]($read_only_style)"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " [ro]"
read_only_style = "fg:#8F929B"

[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
symbol = "⎇ "
style = "fg:#8F929B"
format = "[$symbol$branch]($style)"

[git_status]
style = "fg:#8F929B"
format = " [$all_status$ahead_behind]($style)"

[character]
success_symbol = "[❯](fg:#F2EFE9 bold) "
error_symbol = "[❯](fg:#D18E86 bold) "
vimcmd_symbol = "[❮](fg:#F2EFE9 bold) "
