# Grayscale Graphite terminal palette, adapted from
# https://github.com/andres-guzman/grayscale-graphite

background = #141415
foreground = #d1d0d2
cursor-color = #e0e0e1
cursor-text = #141415
selection-background = #383739
selection-foreground = #e0e0e1

palette = 0=#141415
palette = 1=#792a52
palette = 2=#474649
palette = 3=#4d4b4e
palette = 4=#474649
palette = 5=#4d4b4e
palette = 6=#565558
palette = 7=#d1d0d2
palette = 8=#4d4b4e
palette = 9=#7a787d
palette = 10=#8a878c
palette = 11=#99979b
palette = 12=#8a878c
palette = 13=#99979b
palette = 14=#aba9ad
palette = 15=#e0e0e1
