eval "$(/opt/homebrew/bin/brew shellenv)"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(starship init zsh)"
export PATH="$HOME/.local/bin:$PATH"

# Load secrets from untracked file
[[ -f ~/.secrets ]] && source ~/.secrets

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/natori/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/natori/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/natori/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/natori/google-cloud-sdk/completion.zsh.inc'; fi
